# Generated by Django 4.0.5 on 2022-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Address1',
            new_name='ord_Address1',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Address2',
            new_name='ord_Address2',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='city',
            new_name='ord_city',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='ord_email',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='ord_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='phone_no',
            new_name='ord_phone_no',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='state',
            new_name='ord_state',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='zip',
            new_name='ord_zip_code',
        ),
    ]
