# Generated by Django 4.0.5 on 2022-08-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_address1_orders_ord_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ord_Address2',
        ),
    ]
