# Generated by Django 4.0.5 on 2022-08-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orders_ord_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ord_Address1',
            new_name='ord_Address',
        ),
    ]
