# Generated by Django 4.0.5 on 2022-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_ord_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ord_amount',
            field=models.IntegerField(default=0),
        ),
    ]
